name: ci-golang-workflow
on:
  pull_request:
    branches:
      - dev
jobs:
  check-applications:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.14", "1.19"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
